//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTareas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int Id_Tarea { get; set; }
        public string Titulo_Tarea { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Termino { get; set; }
        public int Habilitado { get; set; }
        public int Id_Categoria { get; set; }
        public int Id_Estado { get; set; }
        public int Id_NivelUrgencia { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual NivelUrgencia NivelUrgencia { get; set; }
    }
}
