//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaTareas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int IdTarea { get; set; }
        public string TituloTarea { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Habilitada { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public Nullable<int> IdNivelUrgencia { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual NivelUrgencia NivelUrgencia { get; set; }
    }
}
